# Generated by Django 2.1.5 on 2023-05-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0003_auto_20230521_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
