# Generated by Django 2.1.5 on 2023-05-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0004_remove_profile_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ImageModel',
        ),
    ]
