# Generated by Django 2.1.5 on 2023-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0005_auto_20230522_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
